networks:
  ychinsta:
    external: false

services:
  webserver:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ychinsta_wevserver
    env_file: ./.env
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ".:/workspace"
    networks:
      - ychinsta
    command: uvicorn main:app --port 8080 --host 0.0.0.0 --reload
